---
abstract: 'Absraction Library for ServiceNow JSON WebServices'
author:
  - 'Kevin L. Kane <kkane@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ServiceNow-JSON
no_index:
  directory:
    - t
    - inc
requires:
  JSON: 0.01
  MIME::Base64: 0.01
  Moose: 0.01
  REST::Client: 0.01
version: 0.01
